### ISSUE TITLE
Assembler message on Ubuntu 18.04

### ISSUE THREAD

**Issue by arruah** [xoreaxeaxeax/rosenbridge#5]
I get the error after this gcc demo.c -o demo

demo.c:11: Error: `bound' is not supported in 64-bit mode

**Comment by jwilk** [comment]
You need to pass `-m32` to the compiler.

**Comment by mathieujobin** [comment]
I have added `-m32` to the Makefile under the `util` folder.
but I am still getting a compilation error on Ubuntu 18.04

```
mathieu:util :-) (master) $ make 
mkdir -p bin
gcc -m32 check.c -o ./bin/check
In file included from check.c:2:0:
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
 #include <bits/libc-header-start.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:4: recipe for target 'bin/check' failed
make: *** [bin/check] Error 1
mathieu:util :-( 1 (master) $ 
```

please advise

**Comment by mathieujobin** [comment]
that file seems to be a 64 only flag, which is what is causing it to be missing with `m32` flag

/usr/include/x86_64-linux-gnu/bits/libc-header-start.h

**Comment by jwilk** [comment]
>```
>/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
>```

Looks like you don't have 32-bit glibc development package installed.
I believe on Ubuntu the package name is `libc6-dev-i386`.

**Comment by mathieujobin** [comment]
Thank you, I can confirm compilation works with ubuntu 18.04

```
$ sudo apt install libc6-dev-i386
$ make 
mkdir -p bin
gcc -m32 check.c -o ./bin/check
$ ./bin/check 
! failed to open /dev/cpu/0/msr
$
```

does that mean I am not vulnerable?

**Comment by jwilk** [comment]
> ```
> $ ./bin/check 
> ! failed to open /dev/cpu/0/msr
> ```
> 
> does that mean I am not vulnerable?

No; the program didn't check anything, because it couldn't open the device it needed.
It's most likely because you didn't have the `msr` kernel module loaded.

**Comment by brammittendorff-dd** [comment]
@jwilk @mathieujobin  you can load the `msr` kernel module with `sudo modprobe msr`. If you watch the video closely you will see he loads it up to: https://youtu.be/_eSAF_qT_FY?t=47m38s
